### ISSUE TITLE
Organize code as a workspace with separate lib and bin

### ISSUE THREAD

**Issue by yuhanfang** [foonetic/agnostic-orderbook#4]
- Allow the lib dependencies to float with downstream users like dex-v4.
- Pin the bin dependencies so that the on-chain program deployment is reproducible.

**Comment by lidatong** [comment]
thinking about this, the boundary between what should live in the crate and what should live in the program is not totally clear-cut. for example, where should `AoError` live? initially i said "crate: it's a library-specific error", but it may not be so clear-cut because the error itself is leaky with on-chain specific things like "does not own the account"

refactor will be easy when they share a `workspace`, so doing a first pass just to separate them out

**Comment by yuhanfang** [comment]
Yeah I think for now minimizing what's in the bin crate makes sense, i.e. only the entrypoint. Everything else can prob live in the lib.
